### ISSUE TITLE
uwagi

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/videoManager#1]
**struktura**
wszedzie robisz angular.module('videoManagerApp').{ bindowanie elementu, np kontrollera }
powinienes porozbijac to na moduly, ktore pozniej przekazesz przez dependencje do videoManagerApp w app.js

pliki kontrollera nazywaj z koncowka -controller.js, serwisu z -service.js, dyrektywy z -directive.js

zamiast 
```javascript
angular.module('videoManagerApp').controller('detailsCtrl',['sth', 'sth2', function (sth, sth2) {
// cialo funkcji
}]);
```
rob
```javascript
function detailsCtrl(sth, sth2) { 
// cialo funkcji
}
angular.module('videoManagerApp').controller('detailsCtrl',['sth', 'sth2', detailsCtrl]);
```
musisz tylko pamietac, zeby albo pojedyncze elementy zamykac w IIFE albo zeby build zamykal Ci calosc w IIFE.

**app.js**
zamiast
```javascript
controller: 'detailsCtrl',
controllerAs: 'details'
```

mozesz po prostu napisac:
```javascript
controller: 'detailsCtrl as details'
```

dodatkowo nie korzystaj z ngRoute. zamiast tego uzyj:
https://github.com/angular-ui/ui-router
dzieki temu bedziesz mogl uzyc metody resolve, ktora sprawi, ze nie bedziesz musial odwolywac sie do $routeParams wewnatrz kontrolera a bedziesz mogl przekazywac 

**filters.js**
```javascript
begin = Number(begin);
```
nigdy nie rob numeru przez Number() (swoja droga jak juz to powinienes uzyc new Number() ale to tez zlo).
http://stackoverflow.com/questions/1133770/how-do-i-convert-a-string-into-an-integer-in-javascript
unary + to najlepszy sposob

**services.js**
. porozbijaj to na pliki - jeden serwis jeden plik

```javascript
if (localStorage[key]) { return JSON.parse(localStorage[key]); }
return null;
```

mozesz to zamienic na ternary operator i zrobic
```javascript
return (localStorage[key]) ? JSON.parse(localStorage[key]) : null;
```

. zamiast zapisywac caly serwis w ten sposob:
```javascript
service.save = function(key, value){
	localStorage[key] = JSON.stringify(value);
};
``` 

lepiej zrob:
```javascript
function save(key, value){
	localStorage[key] = JSON.stringify(value);
};

service.save = save;
```

a jeszcze lepiej korzystaj z revealing module pattern (przerabialismy to przy image-processing:
```javascript
function save(key, value){
	localStorage[key] = JSON.stringify(value);
};

function load(key) {
   return (localStorage[key]) ? JSON.parse(localStorage[key]) : null;
};

return {
  save: save,
  load: load
}
```
(dotyczy to kazdego serwisu)

myVideoService powinienes rozbic na 2 moduly. pierwszy youtubeVideo drugi po prostu video (moze byc myVideo, jak teraz). 
w youtubeVideo powinna byc logika do pobierania filmow, czyli np: get(videoId), getVideoData(videoId), etc. w myVideos powinny byc analogiczne akcje typu get, getVideoData (wykorzystujace youtubeVideo do pobierania danych), ale tez: save(), getVideos() wykorzystujace myStorage do zapisu i odczytu.

dzieki temu nie mieszasz odpowiedzialnosci a kazdy serwis odpowiada Ci tak naprawde za jedna rzecz. przeczytaj o zasadach SOLID: https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)

pomysl sobie, ze niedlugo moze bedziesz musial dodac do tego pobieranie filmow z innych zrodel, np. vimeo / twitch / whatever. musisz wiec sprawic, zeby myVideo, posiadal jak najwieksza abstrakcje, a cala logika powinna byc wydzielona do serwisow posiadajacych takie same interfejsy. 

przeczytaj jak dziala bridge (rzadziej uzywany) i strategy pattern (czesciej):
http://www.dofactory.com/javascript/bridge-design-pattern
http://www.dofactory.com/javascript/strategy-design-pattern

i w jakich celach sa uzywane

**details.js**
vm.iFrame powinienes zamienic na dyrektywe i uzywac tego w htmlu zamiast robic z tego embeda w kontrolerze.

**main.html**
pager - opcja liczby elementow na stronie (4,8,12,16) powinna byc okreslona w konfigu do modulu i wyswietlona przez ng-repeat (dzieki temu nie masz konfiguracji w milionie miejsc

pewnie znajde jeszcze sporo uwag, ale poki co sfixuj to. pozniej bedziemy pracowac nad reszta :)

**Comment by konradkukier2** [comment]
1) struktura - porozbijane na moduly, pozamykane w IIFE wg styleguide
2) app.js (controllerAs) - done
3) services.js - serwisy porozbijane, jeden plik = jeden serwis, myVideoService oddzielony od czesci odpowiedzialnej strice za YouTube, wszystko ulozone w Revealing MP
4) vm.iFrame - nie do konca mam pomysl jak to zrobic, jutro poczytam wiecej o dyrektywach
5) pager - zrobiona opcja konfiguracji ilosci przyciskow
6) ui-router - zainstalowalem, podstawy zrobilem (mam dwa state, list (lista miniaturek video) oraz details (detale pojedynczego video), ale nie rozumiem jak mam uzyc resolve zeby przekazac vidId do $stateParams (?) i potem z tego korzystac

**Comment by konradkukier2** [comment]
re 4) ogarniete, iFrame siedzi teraz jako template w nowej dyrektywie

re 6) dzieki za pomoc, juz widze czego mi brakowalo

Czekam na nastepne uwagi.
